// apps/wknd-svelte/src/components/Card.svelte
<script lang="ts">
  import './Card.css';

  const { general } = $props<{
    general: {
      image?: string;
      title: string;
      description: string;
    };
  }>();
</script>

<div class="card">
  <img src={general.image} alt="Card image" class="card-image" />
  <div class="card-body">
    <h3 class="card-title">{general.title}</h3>
    <p class="card-description">{general.description}</p>
  </div>
</div>

// apps/wknd-react/src/components/Card.tsx
import './Card.css';

type CardProps = {
  general: {
    image?: string;
    title: string;
    description: string;
  };
};

export const Card = ({ general }: CardProps) => {
  const { image, title, description } = general;
  return (
    <div className="card">
      <img src={image} alt="Card image" className="card-image" />

      <div className="card-body">
        <h3 className="card-title">{title}</h3>

        <p className="card-description">{description}</p>
      </div>
    </div>
  );
};
