// apps/wknd-vue/src/components/RichTextWrapper.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useLumaComponent } from '../lib/luma-preview';

const props = defineProps<{
  id: string;
  general?: { body?: string };
  [key: string]: unknown;
}>();

const live = useLumaComponent<typeof props>(props.id);
const data = computed(() => live.value ?? props);
const body = computed(() => data.value.general?.body ?? '<p>Rich text content</p>');
</script>

<template>
  <section style="padding: 2rem; max-width: 760px; margin: 0 auto;">
    <div v-html="body" />
  </section>
</template>

// apps/wknd-react/src/components/RichTextWrapper.tsx
import { MapTo, useLumaComponent } from '../lib/luma-preview';

type RichTextData = {
  id: string;
  general?: { body?: string };
  [key: string]: unknown;
};

function RichTextWrapper(props: RichTextData) {
  const live = useLumaComponent<RichTextData>(props.id);
  const data = live ?? props;
  const body = data.general?.body ?? '<p>Rich text content</p>';

  return (
    <section style={{ padding: '2rem', maxWidth: '760px', margin: '0 auto' }}>
      <div dangerouslySetInnerHTML={{ __html: body }} />
    </section>
  );
}

MapTo('wknd/components/richText', RichTextWrapper);
