// apps/wknd-angular/src/lib/luma-preview.ts
// ─── Luma Preview — Angular adapter ───────────────────────────────────────────
//
// Angular-specific layer. All framework-agnostic logic lives in luma-core.ts.
// Import MapTo + LumaPageComponent here; drop luma-core.ts alongside and copy
// this lib/ folder into any Angular site — then update import-components.ts.

import {
  AfterViewInit,
  Component,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  SimpleChanges,
  Type,
  ViewChild,
  ViewContainerRef,
  computed,
  inject,
  signal,
} from '@angular/core';
import {
  CSS,
  MODE,
  endInstanceDrag,
  extractSectionData,
  fetchPageBySlug,
  getCurrentDrag,
  getPageSlugFromUrl,
  getZoneComponents,
  handleDropOnBar,
  hasContent,
  initPostMessageBridge,
  notifyAddComponent,
  notifyInstanceClick,
  offDragChange,
  onDragChange,
  setCurrentDrag,
  sortByOrder,
  startInstanceDrag,
  type ComponentData,
  type ComponentPayload,
  type PageModel,
  type PageModelPayload,
  type ZoneInfo,
} from './luma-core';

// ── Component registry ────────────────────────────────────────────────────────

type RegistryEntry = {
  component: Type<any>;
  displayName?: string;
  placeholder?: string;
};

const componentRegistry: Record<string, RegistryEntry> = {};

export function MapTo(
  namespace: string,
  component: Type<any>,
  config: { displayName?: string; placeholder?: string } = {},
): void {
  componentRegistry[namespace] = { component, ...config };
}

export function getRegistry() {
  return componentRegistry;
}

// ── Helper: convert style object to CSS text ──────────────────────────────────

function toStyle(obj: Record<string, string | number>): string {
  return Object.entries(obj)
    .map(([k, v]) => {
      const prop = k.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
      return `${prop}:${typeof v === 'number' && !['zIndex', 'fontWeight', 'opacity'].includes(k) ? `${v}px` : v}`;
    })
    .join(';');
}

// ── DropBarComponent ──────────────────────────────────────────────────────────

@Component({
  selector: 'luma-drop-bar',
  standalone: true,
  template: `<div [attr.style]="style()" (dragover)="onDragOver($event)" (dragleave)="over.set(false)" (drop)="onDrop($event)"></div>`,
})
export class DropBarComponent {
  @Input() afterIndex: number | null = null;
  @Input({ required: true }) zoneId!: string;
  @Input() zoneMaxComponents: number | null = null;
  @Input({ required: true }) zoneComponentCount!: number;

  over = signal(false);
  style = computed(() =>
    this.over() ? toStyle({ ...CSS.dropBar, ...CSS.dropBarActive }) : toStyle({ ...CSS.dropBar }),
  );

  onDragOver(e: DragEvent) {
    if (!getCurrentDrag() || !this.zoneMaxComponents || this.zoneComponentCount < this.zoneMaxComponents) {
      e.preventDefault();
      e.stopPropagation();
      this.over.set(true);
    }
  }

  onDrop(e: DragEvent) {
    e.preventDefault();
    e.stopPropagation();
    this.over.set(false);
    handleDropOnBar(this.afterIndex, this.zoneId, this.zoneMaxComponents, this.zoneComponentCount);
  }
}

// ── AddComponentButtonComponent ───────────────────────────────────────────────

@Component({
  selector: 'luma-add-button',
  standalone: true,
  template: `<button [attr.style]="btnStyle" (click)="onClick()">+ Add Component</button>`,
})
export class AddComponentButtonComponent {
  @Input({ required: true }) zoneId!: string;
  @Input() afterIndex: number | null = null;

  btnStyle = toStyle({ ...CSS.addButton });

  onClick() {
    notifyAddComponent(this.zoneId, this.afterIndex);
  }
}

// ── EmptyZoneDropTargetComponent ──────────────────────────────────────────────

@Component({
  selector: 'luma-empty-zone',
  standalone: true,
  template: `
    <div
      [attr.style]="style()"
      (dragover)="onDragOver($event)"
      (dragleave)="over.set(false)"
      (drop)="onDrop($event)">
      {{ label() }}
    </div>`,
})
export class EmptyZoneDropTargetComponent implements OnInit, OnDestroy {
  @Input({ required: true }) zoneName!: string;
  @Input({ required: true }) locked!: boolean;

  over = signal(false);
  anyDragging = signal(false);

  private _onDragChange = (d: boolean) => this.anyDragging.set(d);

  label = computed(() => {
    if (this.locked) return `${this.zoneName} — locked`;
    if (this.anyDragging()) return `Drop here → ${this.zoneName}`;
    return `Drop components here into ${this.zoneName}`;
  });

  style = computed(() => {
    if (!this.anyDragging() || this.locked) return toStyle({ ...CSS.emptyZone });
    return this.over()
      ? toStyle({ ...CSS.emptyZone, ...CSS.emptyZoneActive })
      : toStyle({ ...CSS.emptyZone, borderColor: '#6366f1' });
  });

  ngOnInit() { onDragChange(this._onDragChange); }
  ngOnDestroy() { offDragChange(this._onDragChange); }

  onDragOver(e: DragEvent) {
    if (this.anyDragging() && !this.locked) {
      e.preventDefault();
      e.stopPropagation();
      this.over.set(true);
    }
  }

  onDrop(e: DragEvent) {
    e.preventDefault();
    e.stopPropagation();
    this.over.set(false);
    setCurrentDrag(null);
  }
}

// ── EditableWrapperComponent ──────────────────────────────────────────────────

@Component({
  selector: 'luma-editable',
  standalone: true,
  imports: [DropBarComponent],
  template: `
    <div>
      @if (showDropBar()) {
        <luma-drop-bar
          [afterIndex]="index - 1"
          [zoneId]="zoneId"
          [zoneMaxComponents]="zoneMaxComponents"
          [zoneComponentCount]="zoneComponentCount" />
      }
      <div
        style="position:relative"
        (mouseenter)="hovered.set(true)"
        (mouseleave)="hovered.set(false)">
        <ng-container #innerHost />
        <div
          [attr.style]="overlayStyle()"
          draggable="true"
          (dragstart)="onDragStart($event)"
          (dragend)="onDragEnd()"
          (click)="onClick($event)">
        </div>
        @if (hovered()) {
          <button [attr.style]="badgeStyle" (click)="onBadgeClick($event)">
            Edit · {{ displayName() }}
          </button>
        }
      </div>
    </div>`,
})
export class EditableWrapperComponent implements OnInit, AfterViewInit, OnChanges, OnDestroy {
  @Input({ required: true }) instance!: ComponentData;
  @Input({ required: true }) componentType!: string;
  @Input({ required: true }) index!: number;
  @Input({ required: true }) zoneId!: string;
  @Input() zoneMaxComponents: number | null = null;
  @Input({ required: true }) zoneComponentCount!: number;

  @ViewChild('innerHost', { read: ViewContainerRef }) innerHost!: ViewContainerRef;

  private compRef: any = null;
  private isDraggingThis = false;
  private componentEventHandler = (e: Event) => {
    const payload = (e as CustomEvent<ComponentPayload>).detail;
    if (this.compRef) {
      Object.keys(payload.config).forEach((k) => {
        try { this.compRef.setInput(k, payload.config[k]); } catch { /* skip undeclared */ }
      });
    }
  };
  private _onDragChange = (d: boolean) => this.anyDragging.set(d);

  hovered = signal(false);
  anyDragging = signal(false);
  showDropBar = computed(() => this.anyDragging() && !this.isDraggingThis);

  displayName = computed(() => componentRegistry[this.componentType]?.displayName ?? '');
  overlayStyle = computed(() =>
    toStyle({ ...CSS.overlay, ...(this.hovered() ? CSS.overlayHover : {}) }),
  );
  badgeStyle = toStyle({ ...CSS.editBadge });

  ngOnInit() {
    onDragChange(this._onDragChange);
    window.addEventListener(`luma:component:${this.instance.id}`, this.componentEventHandler);
  }

  ngAfterViewInit() {
    this.renderInner();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['instance'] && !changes['instance'].firstChange) {
      this.renderInner();
    }
  }

  ngOnDestroy() {
    offDragChange(this._onDragChange);
    window.removeEventListener(`luma:component:${this.instance.id}`, this.componentEventHandler);
    this.compRef?.destroy();
  }

  private renderInner() {
    this.innerHost.clear();
    this.compRef = null;
    const entry = componentRegistry[this.componentType];
    const config = this.instance.config as Record<string, unknown>;

    if (!hasContent(config) || !entry) return;

    const ref = this.innerHost.createComponent(entry.component);
    Object.entries(config).forEach(([k, v]) => {
      try { ref.setInput(k, v); } catch { /* skip undeclared inputs */ }
    });
    this.compRef = ref;
  }

  onDragStart(e: DragEvent) {
    this.isDraggingThis = true;
    startInstanceDrag(this.instance.id, this.index, this.zoneId, e.dataTransfer!);
    setTimeout(() => this.hovered.set(false), 0);
  }

  onDragEnd() {
    this.isDraggingThis = false;
    endInstanceDrag();
  }

  onClick(e: MouseEvent) {
    e.stopPropagation();
    notifyInstanceClick(this.instance.id, this.instance.componentId);
  }

  onBadgeClick(e: MouseEvent) {
    e.stopPropagation();
    notifyInstanceClick(this.instance.id, this.instance.componentId);
  }
}

// ── PageRendererComponent ─────────────────────────────────────────────────────

@Component({
  selector: 'luma-page-renderer',
  standalone: true,
  imports: [EditableWrapperComponent, EmptyZoneDropTargetComponent, AddComponentButtonComponent, DropBarComponent],
  template: `
    @if (isEditMode) {
      <div>
        @for (zone of sortedZones(); track zone.id) {
          @let zoneCmps = componentsByZone()(zone.id);
          <div>
            @if (zoneCmps.length === 0) {
              <luma-empty-zone [zoneName]="zone.name" [locked]="zone.locked" />
              @if (!zone.locked) {
                <luma-add-button [zoneId]="zone.id" [afterIndex]="null" />
              }
            } @else {
              @for (comp of zoneCmps; track comp.id; let i = $index) {
                <luma-editable
                  [instance]="comp"
                  [componentType]="comp.type"
                  [index]="i"
                  [zoneId]="zone.id"
                  [zoneMaxComponents]="zone.maxComponents"
                  [zoneComponentCount]="zoneCmps.length" />
              }
              <luma-drop-bar
                [afterIndex]="zoneCmps.length - 1"
                [zoneId]="zone.id"
                [zoneMaxComponents]="zone.maxComponents"
                [zoneComponentCount]="zoneCmps.length" />
              @if (!zone.locked) {
                <luma-add-button
                  [zoneId]="zone.id"
                  [afterIndex]="zoneCmps.length - 1" />
              }
            }
          </div>
        }
      </div>
    } @else {
      <main>
        <ng-container #previewHost />
      </main>
    }`,
})
export class PageRendererComponent implements OnInit, OnDestroy, OnChanges {
  @Input() components: ComponentData[] = [];

  private vcr = inject(ViewContainerRef);
  private previewRefs: any[] = [];

  readonly isEditMode = MODE === 'edit';

  zones = signal<ZoneInfo[]>([]);
  allComponents = signal<ComponentData[]>([]);

  sortedZones = computed(() => sortByOrder(this.zones()));
  componentsByZone = computed(() => {
    const all = this.allComponents();
    return (zoneId: string) => getZoneComponents(all, zoneId);
  });

  private pageModelHandler = (e: Event) => {
    const payload = (e as CustomEvent<PageModelPayload>).detail;
    this.zones.set(payload.zones);
    this.allComponents.set(payload.components);
  };

  ngOnInit() {
    if (this.isEditMode) {
      window.addEventListener('luma:pageModel', this.pageModelHandler);
    } else {
      this.renderPreview(this.components);
    }
  }

  ngOnChanges(changes: SimpleChanges) {
    if (!this.isEditMode && changes['components']) {
      this.renderPreview(this.components);
    }
  }

  ngOnDestroy() {
    window.removeEventListener('luma:pageModel', this.pageModelHandler);
    this.clearPreview();
  }

  private clearPreview() {
    this.previewRefs.forEach((r) => r.destroy());
    this.previewRefs = [];
    this.vcr.clear();
  }

  private renderPreview(items: ComponentData[]) {
    this.clearPreview();
    sortByOrder(items).forEach((comp) => {
      const entry = componentRegistry[comp.type];
      if (!entry) {
        console.warn(`[Luma] No component registered for type "${comp.type}"`);
        return;
      }
      const ref = this.vcr.createComponent(entry.component);
      const sectionData = extractSectionData(comp);
      Object.entries(sectionData).forEach(([k, v]) => {
        try { ref.setInput(k, v); } catch { /* skip undeclared inputs */ }
      });
      this.previewRefs.push(ref);
    });
  }
}

// ── LumaPageComponent ─────────────────────────────────────────────────────────
// Top-level component. Initialises postMessage bridge, fetches in preview mode.

@Component({
  selector: 'luma-page',
  standalone: true,
  imports: [PageRendererComponent],
  template: `
    @if (error()) {
      <div style="padding:2rem;color:#dc2626">Error: {{ error() }}</div>
    } @else if (!page() && !isEditMode) {
      <div style="padding:2rem;color:#94a3b8">Loading…</div>
    } @else {
      <luma-page-renderer [components]="page()?.components ?? []" />
    }`,
})
export class LumaPageComponent implements OnInit, OnDestroy {
  readonly isEditMode = MODE === 'edit';
  page = signal<PageModel | null>(null);
  error = signal<string | null>(null);

  private cleanup?: () => void;

  async ngOnInit() {
    this.cleanup = initPostMessageBridge();
    if (this.isEditMode) return;
    const slug = getPageSlugFromUrl();
    if (!slug) { this.error.set('No page slug in URL path'); return; }
    try {
      this.page.set(await fetchPageBySlug(slug));
    } catch (err) {
      this.error.set(String(err));
    }
  }

  ngOnDestroy() { this.cleanup?.(); }
}

export type { ComponentData, ZoneInfo, PageModel };

// apps/wknd-react/src/lib/luma-preview.tsx
// ─── Luma Preview — React adapter ────────────────────────────────────────────
//
// React-specific layer. All framework-agnostic logic lives in luma-core.ts.
// Import MapTo + LumaProvider + Page here; drop luma-core.ts alongside for
// other framework adapters (Vue, Angular, Svelte, etc.) to share.

import type { CSSProperties, ComponentType } from 'react';
import { useEffect, useRef, useState } from 'react';
import {
  CSS,
  MODE,
  canZoneAccept,
  endInstanceDrag,
  extractSectionData,
  fetchPageBySlug,
  getCurrentDrag,
  getPageSlugFromUrl,
  getZoneComponents,
  handleDropOnBar,
  hasContent,
  initPostMessageBridge,
  notifyAddComponent,
  notifyInstanceClick,
  offDragChange,
  onDragChange,
  setCurrentDrag,
  sortByOrder,
  startInstanceDrag,
  type ComponentData,
  type ComponentPayload,
  type PageModel,
  type PageModelPayload,
  type ZoneInfo,
} from './luma-core';

// ── Component registry ────────────────────────────────────────────────────────
// React-specific: stores ComponentType references.

type MapToConfig = {
  placeholder?: string;
  displayName?: string;
};

type RegistryEntry = {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  Component: ComponentType<any>;
  config: MapToConfig;
};

const componentRegistry: Record<string, RegistryEntry> = {};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function MapTo(namespace: string, component: ComponentType<any>, config: MapToConfig = {}): void {
  componentRegistry[namespace] = { Component: component, config };
}

// ── useLumaMode ───────────────────────────────────────────────────────────────

export function useLumaMode(): 'edit' | 'preview' {
  return MODE;
}

// ── LumaProvider ──────────────────────────────────────────────────────────────
// Mount once at the app root. Initialises the postMessage bridge.

export function LumaProvider({ children }: { children: React.ReactNode }) {
  useEffect(() => initPostMessageBridge(), []);
  return <>{children}</>;
}

// ── DropBar ───────────────────────────────────────────────────────────────────

function DropBar({
  afterIndex,
  zoneId,
  zoneMaxComponents,
  zoneComponentCount,
}: {
  afterIndex: number | null;
  zoneId: string;
  zoneMaxComponents: number | null;
  zoneComponentCount: number;
}) {
  const [over, setOver] = useState(false);

  const handleDragOver = (e: React.DragEvent) => {
    if (!getCurrentDrag() || !canZoneAccept(zoneMaxComponents, zoneComponentCount)) return;
    e.preventDefault();
    e.stopPropagation();
    setOver(true);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setOver(false);
    handleDropOnBar(afterIndex, zoneId, zoneMaxComponents, zoneComponentCount);
  };

  return (
    <div
      style={(over ? { ...CSS.dropBar, ...CSS.dropBarActive } : CSS.dropBar) as CSSProperties}
      onDragOver={handleDragOver}
      onDragLeave={() => setOver(false)}
      onDrop={handleDrop}
    />
  );
}

// ── EditableWrapper ───────────────────────────────────────────────────────────
// Subscribes to luma:component:<id> events to update its own content in place.

function EditableWrapper({
  instance: initialInstance,
  componentType,
  index,
  zoneId,
  zoneMaxComponents,
  zoneComponentCount,
}: {
  instance: ComponentData;
  componentType: string;
  index: number;
  zoneId: string;
  zoneMaxComponents: number | null;
  zoneComponentCount: number;
}) {
  const [hovered, setHovered] = useState(false);
  const [anyDragging, setAnyDragging] = useState(false);
  const [liveConfig, setLiveConfig] = useState<Record<string, unknown> | null>(null);
  const isDraggingThis = useRef(false);

  useEffect(() => {
    onDragChange(setAnyDragging);
    return () => offDragChange(setAnyDragging);
  }, []);

  useEffect(() => {
    const handler = (e: Event) => {
      setLiveConfig((e as CustomEvent<ComponentPayload>).detail.config);
    };
    window.addEventListener(`luma:component:${initialInstance.id}`, handler);
    return () => window.removeEventListener(`luma:component:${initialInstance.id}`, handler);
  }, [initialInstance.id]);

  const entry = componentRegistry[componentType];
  const displayName = entry?.config?.displayName ?? '';
  const instance = liveConfig !== null ? { ...initialInstance, config: liveConfig } : initialInstance;

  const showDropBars = anyDragging && !isDraggingThis.current;

  return (
    <>
      {showDropBars && (
        <DropBar
          afterIndex={index - 1}
          zoneId={zoneId}
          zoneMaxComponents={zoneMaxComponents}
          zoneComponentCount={zoneComponentCount}
        />
      )}
      <div
        style={{ position: 'relative' }}
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
      >
        {!hasContent(instance.config) ? (
          <div style={CSS.placeholderCard as CSSProperties}>
            {entry?.config?.placeholder ?? `${displayName} — click Edit to add content`}
          </div>
        ) : entry ? (
          <entry.Component id={instance.id} {...instance.config} />
        ) : (
          <div style={{ padding: '1rem', color: '#dc2626', fontSize: 13 }}>
            [Luma] No component registered for &quot;{componentType}&quot;
          </div>
        )}
        <div
          style={{ ...CSS.overlay, ...(hovered ? CSS.overlayHover : {}) } as CSSProperties}
          draggable
          onDragStart={(e) => {
            isDraggingThis.current = true;
            startInstanceDrag(initialInstance.id, index, zoneId, e.dataTransfer);
            setTimeout(() => setHovered(false), 0);
          }}
          onDragEnd={() => {
            isDraggingThis.current = false;
            endInstanceDrag();
          }}
          onClick={(e) => {
            e.stopPropagation();
            notifyInstanceClick(instance.id, instance.componentId);
          }}
        />
        {hovered && (
          <button
            style={CSS.editBadge as CSSProperties}
            onClick={(e) => {
              e.stopPropagation();
              notifyInstanceClick(instance.id, instance.componentId);
            }}
          >
            Edit · {displayName}
          </button>
        )}
      </div>
    </>
  );
}

// ── EmptyZoneDropTarget ────────────────────────────────────────────────────────

function EmptyZoneDropTarget({ zoneName, locked }: { zoneName: string; locked: boolean }) {
  const [over, setOver] = useState(false);
  const [anyDragging, setAnyDragging] = useState(false);

  useEffect(() => {
    onDragChange(setAnyDragging);
    return () => offDragChange(setAnyDragging);
  }, []);

  if (!anyDragging || locked) {
    return (
      <div style={CSS.emptyZone as CSSProperties}>
        {locked ? `${zoneName} — locked` : `Drop components here into ${zoneName}`}
      </div>
    );
  }

  return (
    <div
      style={(over ? { ...CSS.emptyZone, ...CSS.emptyZoneActive } : { ...CSS.emptyZone, borderColor: '#6366f1' }) as CSSProperties}
      onDragOver={(e) => { e.preventDefault(); e.stopPropagation(); setOver(true); }}
      onDragLeave={() => setOver(false)}
      onDrop={(e) => {
        e.preventDefault();
        e.stopPropagation();
        setOver(false);
        setCurrentDrag(null);
      }}
    >
      Drop here → {zoneName}
    </div>
  );
}

// ── AddComponentButton ────────────────────────────────────────────────────────

function AddComponentButton({ zoneId, afterIndex }: { zoneId: string; afterIndex: number | null }) {
  return (
    <button
      style={CSS.addButton as CSSProperties}
      onClick={() => notifyAddComponent(zoneId, afterIndex)}
    >
      + Add Component
    </button>
  );
}

// ── PageRenderer ──────────────────────────────────────────────────────────────

function PageRenderer({ components: initialComponents }: { components: ComponentData[] }) {
  const [editData, setEditData] = useState<{ zones: ZoneInfo[]; components: ComponentData[] }>({
    zones: [],
    components: initialComponents,
  });

  useEffect(() => {
    if (MODE !== 'edit') return;
    const handler = (e: Event) => {
      const payload = (e as CustomEvent<PageModelPayload>).detail;
      setEditData({ zones: payload.zones, components: payload.components });
    };
    window.addEventListener('luma:pageModel', handler);
    return () => window.removeEventListener('luma:pageModel', handler);
  }, []);

  // ── Preview mode: flat render ─────────────────────────────────────────────
  // Public API spreads section data directly on the component object.
  // Strip known meta keys; pass everything else as props.
  if (MODE !== 'edit') {
    return (
      <>
        {sortByOrder(initialComponents).map((comp) => {
          const entry = componentRegistry[comp.type];
          if (!entry) return null;
          return <entry.Component key={comp.id} id={comp.id} {...extractSectionData(comp)} />;
        })}
      </>
    );
  }

  // ── Edit mode: zone-aware render driven by CMS postMessage ────────────────
  const { zones, components: allComponents } = editData;

  return (
    <>
      {sortByOrder(zones).map((zone) => {
        const zoneComponents = getZoneComponents(allComponents, zone.id);

        return (
          <div key={zone.id}>
            {zoneComponents.length === 0 ? (
              zone.locked ? (
                <EmptyZoneDropTarget zoneName={zone.name} locked={true} />
              ) : (
                <>
                  <EmptyZoneDropTarget zoneName={zone.name} locked={false} />
                  <AddComponentButton zoneId={zone.id} afterIndex={null} />
                </>
              )
            ) : (
              <>
                {zoneComponents.map((comp, i) => (
                  <EditableWrapper
                    key={comp.id}
                    componentType={comp.type}
                    instance={comp}
                    index={i}
                    zoneId={zone.id}
                    zoneMaxComponents={zone.maxComponents}
                    zoneComponentCount={zoneComponents.length}
                  />
                ))}
                <DropBar
                  afterIndex={zoneComponents.length - 1}
                  zoneId={zone.id}
                  zoneMaxComponents={zone.maxComponents}
                  zoneComponentCount={zoneComponents.length}
                />
                {!zone.locked && (
                  <AddComponentButton zoneId={zone.id} afterIndex={zoneComponents.length - 1} />
                )}
              </>
            )}
          </div>
        );
      })}
    </>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────
// Top-level component. Handles fetch in preview mode; waits for postMessage in edit mode.

export function Page() {
  const [page, setPage] = useState<PageModel | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (MODE === 'edit') return;
    const slug = getPageSlugFromUrl();
    if (!slug) { setError('No page slug in URL path'); return; }
    fetchPageBySlug(slug).then(setPage).catch((err) => setError(err.message));
  }, []);

  if (MODE === 'edit') return <PageRenderer components={[]} />;
  if (error) return <div style={{ padding: '2rem', color: '#dc2626' }}>Error: {error}</div>;
  if (!page) return <div style={{ padding: '2rem', color: '#94a3b8' }}>Loading…</div>;
  return <PageRenderer components={page.components} />;
}

export type { ComponentData, ZoneInfo };
