// apps/wknd-vue/src/components/Header.vue
<script setup lang="ts">
import './Header.css';

type MainMenuNav = {
  menuName: string;
  subMenu: Array<{ menuName: string; url: string; iconName: string }>;
};

const props = defineProps<{
  general: { brandName: string };
  menu1?: MainMenuNav;
  menu2?: MainMenuNav;
}>();

const menus = [props.menu1, props.menu2].filter(Boolean) as MainMenuNav[];
</script>

<template>
  <header>
    <p class="brandName">{{ general.brandName }}</p>
    <ul>
      <li v-for="menu in menus" :key="menu.menuName">{{ menu.menuName }}</li>
    </ul>
  </header>
</template>

// apps/wknd-svelte/src/components/Header.svelte
<script lang="ts">
  import './Header.css';

  type MainMenuNav = {
    menuName: string;
    subMenu: Array<{ menuName: string; url: string; iconName: string }>;
  };

  const { general, menu1, menu2 } = $props<{
    general: { brandName: string };
    menu1?: MainMenuNav;
    menu2?: MainMenuNav;
  }>();

  const menus = [menu1, menu2].filter(Boolean) as MainMenuNav[];
</script>

<header>
  <p class="brandName">{general.brandName}</p>
  <ul>
    {#each menus as menu (menu.menuName)}
      <li>{menu.menuName}</li>
    {/each}
  </ul>
</header>
