// apps/wknd-react/src/components/Header.tsx
import './Header.css';

type HeaderProps = {
  general: {
    brandName: string;
  };
  menu1: MainMenuNav;
  menu2: MainMenuNav;
};

type MainMenuNav = {
  menuName: string;
  subMenu: Array<{
    menuName: string;
    url: string;
    iconName: string;
  }>;
};

export const Header = (props: HeaderProps) => {
  const { general, menu1, menu2 } = props;
  const menus = [menu1, menu2];

  return (
    <header>
      <p className="brandName">{general.brandName}</p>
      <ul>
        {menus.map((menu) => (
          <li key={menu.menuName}>{menu.menuName}</li>
        ))}
      </ul>
    </header>
  );
};

// apps/wknd-vue/src/components/Header.vue
<script setup lang="ts">
import './Header.css';

type MainMenuNav = {
  menuName: string;
  subMenu: Array<{ menuName: string; url: string; iconName: string }>;
};

const props = defineProps<{
  general: { brandName: string };
  menu1?: MainMenuNav;
  menu2?: MainMenuNav;
}>();

const menus = [props.menu1, props.menu2].filter(Boolean) as MainMenuNav[];
</script>

<template>
  <header>
    <p class="brandName">{{ general.brandName }}</p>
    <ul>
      <li v-for="menu in menus" :key="menu.menuName">{{ menu.menuName }}</li>
    </ul>
  </header>
</template>
